Repository SomSomParty/SomSomParty_BE, pull requests merged in 2024-12, with the labels that each got.

#6 Feature/#1 축제 관련 엔티티 구현
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Festival/enums/ReservationStatus.java
  src/main/java/com/acc/somsomparty/domain/Reservation/entity/Reservation.java
  src/main/java/com/acc/somsomparty/domain/User/entity/User.java
  src/main/java/com/acc/somsomparty/domain/User/enums/Role.java
  src/main/java/com/acc/somsomparty/global/common/BaseEntity.java
Labels: ✨ feature

#10 Feature/#1 축제 상세 페이지, 축제 목록 조회 API 구현
  src/main/java/com/acc/somsomparty/domain/Festival/controller/FestivalController.java
  src/main/java/com/acc/somsomparty/domain/Festival/converter/FestivalConverter.java
  src/main/java/com/acc/somsomparty/domain/Festival/dto/FestivalResponseDTO.java
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Festival/repository/FestivalRepository.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryService.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Reservation/entity/Reservation.java
  src/main/java/com/acc/somsomparty/domain/Reservation/enums/ReservationStatus.java
  src/main/java/com/acc/somsomparty/domain/User/entity/User.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
Labels: ✨ feature

#13 Feature/#9 검색 기능 구현
  build.gradle
  src/main/java/com/acc/somsomparty/SomsompartyApplication.java
  src/main/java/com/acc/somsomparty/domain/Festival/controller/FestivalController.java
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Festival/repository/FestivalRepository.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryService.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ✨ feature

#12 Feature/#8 대기열 시스템 구현
  build.gradle
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Queue/config/AwsSQSConfig.java
  src/main/java/com/acc/somsomparty/domain/Queue/config/RedissonConfig.java
  src/main/java/com/acc/somsomparty/domain/Queue/config/SqsSender.java
  src/main/java/com/acc/somsomparty/domain/Queue/controller/UserQueueController.java
  src/main/java/com/acc/somsomparty/domain/Queue/dto/AllowedUserResponse.java
  src/main/java/com/acc/somsomparty/domain/Queue/dto/FestivalWaitingRoomResponse.java
  src/main/java/com/acc/somsomparty/domain/Queue/dto/RankNumberResponse.java
  src/main/java/com/acc/somsomparty/domain/Queue/dto/RegisterUserResponse.java
  src/main/java/com/acc/somsomparty/domain/Queue/service/UserQueueService.java
  src/main/java/com/acc/somsomparty/global/config/RedisConfig.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ feature

#17 Feature/#11 예약 API 구현
  src/main/java/com/acc/somsomparty/domain/Queue/service/UserQueueService.java
  src/main/java/com/acc/somsomparty/domain/Reservation/controller/ReservationController.java
  src/main/java/com/acc/somsomparty/domain/Reservation/converter/ReservationConverter.java
  src/main/java/com/acc/somsomparty/domain/Reservation/dto/ReservationRequestDTO.java
  src/main/java/com/acc/somsomparty/domain/Reservation/dto/ReservationResponseDTO.java
  src/main/java/com/acc/somsomparty/domain/Reservation/entity/Reservation.java
  src/main/java/com/acc/somsomparty/domain/Reservation/enums/ReservationStatus.java
  src/main/java/com/acc/somsomparty/domain/Reservation/repository/ReservationRepository.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationCommandService.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationQueryService.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Ticket/entity/Ticket.java
  src/main/java/com/acc/somsomparty/domain/Ticket/repository/TicketRepository.java
  src/main/java/com/acc/somsomparty/domain/User/repository/UserRepository.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
  src/test/java/com/acc/somsomparty/reservation/service/ReservationServiceTest.java
Labels: ✨ feature

#14 Feature/#7 축제 알림 API 구현
  build.gradle
  src/main/java/com/acc/somsomparty/domain/Festival/repository/FestivalRepository.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryService.java
  src/main/java/com/acc/somsomparty/domain/Notification/config/NotiAWSConfig.java
  src/main/java/com/acc/somsomparty/domain/Notification/entity/FcmToken.java
  src/main/java/com/acc/somsomparty/domain/Notification/enums/DeviceType.java
  src/main/java/com/acc/somsomparty/domain/Notification/projection/FestivalTokenProjection.java
  src/main/java/com/acc/somsomparty/domain/Notification/repository/FcmTokenRepository.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/CredentialService.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/CredentialServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/NotiSQSService.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/NotificationService.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/NotificationServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/SNSService.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/SNSServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feature

#26 Feature/ 내 예약 조회 responseDTO에 축제일 필드 추가
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Reservation/converter/ReservationConverter.java
  src/main/java/com/acc/somsomparty/domain/Reservation/dto/ReservationResponseDTO.java
Labels: ✨ feature

#22 Feature/#20 채팅 Rest API 추가
  build.gradle
  src/main/java/com/acc/somsomparty/domain/Festival/controller/FestivalController.java
  src/main/java/com/acc/somsomparty/domain/Festival/dto/FestivalRequestDTO.java
  src/main/java/com/acc/somsomparty/domain/Festival/entity/Festival.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryService.java
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/User/entity/User.java
  src/main/java/com/acc/somsomparty/domain/chatting/config/DynamoDBConfig.java
  src/main/java/com/acc/somsomparty/domain/chatting/config/JacksonConfig.java
  src/main/java/com/acc/somsomparty/domain/chatting/controller/ChattingController.java
  src/main/java/com/acc/somsomparty/domain/chatting/controller/WebSocketController.java
  src/main/java/com/acc/somsomparty/domain/chatting/dto/ChatRoomCreateEvent.java
  src/main/java/com/acc/somsomparty/domain/chatting/dto/MessageDto.java
  src/main/java/com/acc/somsomparty/domain/chatting/dto/UserChatRoomListDto.java
  src/main/java/com/acc/somsomparty/domain/chatting/entity/ChatRoom.java
  src/main/java/com/acc/somsomparty/domain/chatting/entity/Message.java
  src/main/java/com/acc/somsomparty/domain/chatting/entity/UserChatRoom.java
  src/main/java/com/acc/somsomparty/domain/chatting/eventListener/ChatRoomListener.java
  src/main/java/com/acc/somsomparty/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/acc/somsomparty/domain/chatting/repository/MessageRepository.java
  src/main/java/com/acc/somsomparty/domain/chatting/repository/jpa/UserChatRoomRepository.java
  src/main/java/com/acc/somsomparty/domain/chatting/service/ChattingService.java
  src/main/java/com/acc/somsomparty/domain/chatting/service/KafkaConsumerService.java
  src/main/java/com/acc/somsomparty/domain/chatting/service/KafkaProducerService.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ feature

#25 Feature/#23 회원관리 관련 API 구현
  build.gradle
  src/main/java/com/acc/somsomparty/domain/User/config/CognitoConfig.java
  src/main/java/com/acc/somsomparty/domain/User/controller/UserController.java
  src/main/java/com/acc/somsomparty/domain/User/dto/ConfirmSignUpReqeust.java
  src/main/java/com/acc/somsomparty/domain/User/dto/LoginRequest.java
  src/main/java/com/acc/somsomparty/domain/User/dto/LoginResponse.java
  src/main/java/com/acc/somsomparty/domain/User/dto/RefreshTokenResponse.java
  src/main/java/com/acc/somsomparty/domain/User/dto/SignUpRequest.java
  src/main/java/com/acc/somsomparty/domain/User/entity/User.java
  src/main/java/com/acc/somsomparty/domain/User/repository/UserRepository.java
  src/main/java/com/acc/somsomparty/domain/User/service/UserService.java
  src/main/java/com/acc/somsomparty/domain/User/service/UserServiceImpl.java
  src/main/java/com/acc/somsomparty/global/config/SecurityConfig.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
  src/main/java/com/acc/somsomparty/global/filter/JwtFilter.java
  src/main/java/com/acc/somsomparty/global/util/JwtUtil.java
  src/main/resources/application.yml
Labels: ✨ feature

#31 Feature/#29 안 읽은 메세지 개수
  build.gradle
  src/main/java/com/acc/somsomparty/domain/chatting/dto/MessageDto.java
  src/main/java/com/acc/somsomparty/domain/chatting/dto/UserChatRoomListDto.java
  src/main/java/com/acc/somsomparty/domain/chatting/eventListener/WebSocketListener.java
  src/main/java/com/acc/somsomparty/domain/chatting/service/ChattingService.java
  src/main/java/com/acc/somsomparty/domain/chatting/service/KafkaConsumerService.java
  src/main/java/com/acc/somsomparty/global/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ feature

#30 Feature/ 축제 생성 시 날짜별 티켓 생성, Redis 캐시 무효화
  src/main/java/com/acc/somsomparty/domain/Festival/service/FestivalQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Ticket/entity/Ticket.java
Labels: ✨ feature

#32 Feature/#27 FCM 토큰 관리 API 추가 및 알림 전송 보완
  src/main/java/com/acc/somsomparty/domain/Notification/controller/NotificationController.java
  src/main/java/com/acc/somsomparty/domain/Notification/dto/FcmTokenActivateRequest.java
  src/main/java/com/acc/somsomparty/domain/Notification/dto/FcmTokenDeactivateRequest.java
  src/main/java/com/acc/somsomparty/domain/Notification/entity/FcmToken.java
  src/main/java/com/acc/somsomparty/domain/Notification/enums/TokenState.java
  src/main/java/com/acc/somsomparty/domain/Notification/projection/FestivalTokenProjection.java
  src/main/java/com/acc/somsomparty/domain/Notification/repository/FcmTokenRepository.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/FcmTokenService.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/FcmTokenServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/Notification/service/NotificationServiceImpl.java
  src/main/java/com/acc/somsomparty/global/config/SecurityConfig.java
Labels: ✨ feature

#37 Refactor/#35 로그인한 사용자 정보 받아오기
  src/main/java/com/acc/somsomparty/domain/Queue/controller/UserQueueController.java
  src/main/java/com/acc/somsomparty/domain/Queue/service/UserQueueService.java
  src/main/java/com/acc/somsomparty/domain/Reservation/controller/ReservationController.java
  src/main/java/com/acc/somsomparty/domain/Reservation/dto/ReservationRequestDTO.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationCommandService.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/User/controller/UserController.java
  src/main/java/com/acc/somsomparty/domain/User/service/UserServiceImpl.java
  src/main/java/com/acc/somsomparty/global/config/RedisConfig.java
  src/main/java/com/acc/somsomparty/global/config/SecurityConfig.java
  src/main/java/com/acc/somsomparty/global/exception/CustomException.java
  src/main/java/com/acc/somsomparty/global/exception/error/ErrorCode.java
  src/main/java/com/acc/somsomparty/global/filter/JwtAuthFilter.java
  src/main/java/com/acc/somsomparty/global/filter/JwtExceptionFilter.java
Labels: ✨ feature, :recycle: refactor

#34 Refactor/#33 내 예약 조회 로그인한 사용자 정보 받아오기
  src/main/java/com/acc/somsomparty/domain/Reservation/controller/ReservationController.java
  src/main/java/com/acc/somsomparty/domain/Reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/acc/somsomparty/global/config/SecurityConfig.java
  src/main/java/com/acc/somsomparty/global/config/SwaggerConfig.java
Labels: :recycle: refactor

#41 Refactor/#40 채팅 로그인한 사용자 정보 받아오기
  src/main/java/com/acc/somsomparty/domain/User/controller/UserController.java
  src/main/java/com/acc/somsomparty/domain/User/dto/LoginResponse.java
  src/main/java/com/acc/somsomparty/domain/User/repository/UserRepository.java
  src/main/java/com/acc/somsomparty/domain/User/service/UserServiceImpl.java
  src/main/java/com/acc/somsomparty/domain/chatting/controller/ChattingController.java
Labels: :recycle: refactor
